apiVersion: v1
kind: Service
metadata:
  name: cloud-naitve-go
  labels:
    app:  cloud-naitve-go
    tier: service
spec:
  #use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 8080
  #the selector should match the lables of our pods
  selector:
    app: cloud-naitve-go
      

